<a href="https://colab.research.google.com/github/TejaswiniKashireddy/B21_1425/blob/main/Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
test_scores = np.random.randint(50, 101, size=(4, 4))
print(test_scores)

[[97 75 90 78]
 [79 78 67 53]
 [71 50 78 99]
 [71 93 79 85]]


In [5]:
column_means = np.mean(test_scores, axis=0)
row_means = np.mean(test_scores, axis=1)
print("Column-wise means:", column_means)
print("Row-wise means:", row_means)


Column-wise means: [79.5  74.   78.5  78.75]
Row-wise means: [85.   69.25 74.5  82.  ]


In [6]:
std_dev = np.std(test_scores)
variance = np.var(test_scores)

print("Standard Deviation:", std_dev)
print("Variance:", variance)

Standard Deviation: 13.36375111074731
Variance: 178.58984375


In [7]:
min_value = np.min(test_scores)
max_value = np.max(test_scores)
min_index = np.argmin(test_scores)
max_index = np.argmax(test_scores)

print("Minimum value:", min_value)
print("Maximum value:", max_value)
print("Index of minimum value:", min_index)
print("Index of maximum value:", max_index)

Minimum value: 50
Maximum value: 99
Index of minimum value: 9
Index of maximum value: 11


In [8]:
print("Statistical Analysis Summary:")
print(f"Row-wise means: {row_means}")
print(f"Column-wise means: {column_means}")
print(f"Overall Standard Deviation: {std_dev}")
print(f"Overall Variance: {variance}")
print(f"Global Minimum Value: {min_value} (Index: {min_index})")
print(f"Global Maximum Value: {max_value} (Index: {max_index})")

Statistical Analysis Summary:
Row-wise means: [85.   69.25 74.5  82.  ]
Column-wise means: [79.5  74.   78.5  78.75]
Overall Standard Deviation: 13.36375111074731
Overall Variance: 178.58984375
Global Minimum Value: 50 (Index: 9)
Global Maximum Value: 99 (Index: 11)


In [9]:
rgb_image = np.random.randint(0, 256, size=(3, 3, 3))
print(rgb_image)


[[[ 29 192 242]
  [ 56  32 158]
  [193  78 144]]

 [[202  56 112]
  [117  38 165]
  [ 69 147  60]]

 [[184  84   5]
  [196 244 181]
  [236 160 207]]]


In [10]:
red_channel = rgb_image[:, :, 0]
green_channel = rgb_image[:, :, 1]
blue_channel = rgb_image[:, :, 2]
print("Red Channel:\n", red_channel)
print("Green Channel:\n", green_channel)
print("Blue Channel:\n", blue_channel)


Red Channel:
 [[ 29  56 193]
 [202 117  69]
 [184 196 236]]
Green Channel:
 [[192  32  78]
 [ 56  38 147]
 [ 84 244 160]]
Blue Channel:
 [[242 158 144]
 [112 165  60]
 [  5 181 207]]


In [11]:
red_channel = rgb_image[:, :, 0]
green_channel = rgb_image[:, :, 1]
blue_channel = rgb_image[:, :, 2]
print("Red Channel:\n", red_channel)
print("Green Channel:\n", green_channel)
print("Blue Channel:\n", blue_channel)

Red Channel:
 [[ 29  56 193]
 [202 117  69]
 [184 196 236]]
Green Channel:
 [[192  32  78]
 [ 56  38 147]
 [ 84 244 160]]
Blue Channel:
 [[242 158 144]
 [112 165  60]
 [  5 181 207]]


In [17]:
red_mean = np.mean(red_channel)
green_mean = np.mean(green_channel)
blue_mean = np.mean(blue_channel)
print(f"Average pixel intensity for Red channel: {red_mean}")
print(f"Average pixel intensity for Green channel: {green_mean}")
print(f"Average pixel intensity for Blue channel: {blue_mean}")

Average pixel intensity for Red channel: 142.44444444444446
Average pixel intensity for Green channel: 114.55555555555556
Average pixel intensity for Blue channel: 141.55555555555554


In [18]:
brightness_increase = 50
brightened_image = np.clip(rgb_image + brightness_increase, 0, 255)
print("Brightened Image (clipped at 255):\n", brightened_image)

Brightened Image (clipped at 255):
 [[[ 79 242 255]
  [106  82 208]
  [243 128 194]]

 [[252 106 162]
  [167  88 215]
  [119 197 110]]

 [[234 134  55]
  [246 255 231]
  [255 210 255]]]


In [19]:
print("Statistical Analysis Summary:")
print("Red Channel:\n", red_channel)
print("Green Channel:\n", green_channel)
print("Blue Channel:\n", blue_channel)
print(f"\nAverage pixel intensity for Red channel: {red_mean}")
print(f"Average pixel intensity for Green channel: {green_mean}")
print(f"Average pixel intensity for Blue channel: {blue_mean}")
print("\nBrightened Image (clipped at 255):\n", brightened_image)

Statistical Analysis Summary:
Red Channel:
 [[ 29  56 193]
 [202 117  69]
 [184 196 236]]
Green Channel:
 [[192  32  78]
 [ 56  38 147]
 [ 84 244 160]]
Blue Channel:
 [[242 158 144]
 [112 165  60]
 [  5 181 207]]

Average pixel intensity for Red channel: 142.44444444444446
Average pixel intensity for Green channel: 114.55555555555556
Average pixel intensity for Blue channel: 141.55555555555554

Brightened Image (clipped at 255):
 [[[ 79 242 255]
  [106  82 208]
  [243 128 194]]

 [[252 106 162]
  [167  88 215]
  [119 197 110]]

 [[234 134  55]
  [246 255 231]
  [255 210 255]]]
